### ISSUE TITLE
When is the model release?

### ISSUE THREAD

**Issue by mayank31398** [amazon-science/alexa-teacher-models#2]
Can we get a timeline on when we can get our hands on the model?

**Comment by mayank31398** [comment]
Any updates on this? @jgmf-amazon

**Comment by jgmf-amazon** [comment]
HI @mayank31398 , the model is now available for non-commercial use via SageMaker. Please see the updated readme for details. Thanks for your interest and patience!

**Comment by mayank31398** [comment]
LOL, thats not called a public release. Not really what was claimed in the paper.
<img width="647" alt="Screenshot 2022-11-20 at 4 06 56 AM" src="https://user-images.githubusercontent.com/32954280/202874246-5ce8ba42-24f2-4ab5-9081-ae962f3ffd65.png">
