### ISSUE TITLE
Tutorial: What to do after #9?

### ISSUE THREAD

**Issue by JPhilipp** [amazon-science/alexa-teacher-models#4]
Your tutorial ends with "9. Ensure that your kernel has started, and run the notebook."

Could you please describe in more detail what doing #9 looks like and entails, and then how to run an example prompt of one's own and retrieve the completion?

Thanks!

**Comment by jgmf-amazon** [comment]
Hi @JPhilipp , sorry for the delay in response. We've provided some examples of how to use the model in Section 4 of the notebook covering a few different use cases. You can either modify one of these for your use case or create a new cell following the same pattern.

I'm happy to give some ideas if you are able to share more about your use case and a bit of example input/output. Thanks.

**Comment by JPhilipp** [comment]
Sheesh. I am now charged USD 2,016.55 by Amazon SageMaker even though I didn't even use it in any form after creating the Notebook/ writing above question! I've contacted support. This is crazy.

**Comment by jgmf-amazon** [comment]
I believe the last comment was addressed here: https://github.com/amazon-science/alexa-teacher-models/issues/5
