### ISSUE TITLE
After following the tutorial, I'm now charged over $2000

### ISSUE THREAD

**Issue by JPhilipp** [amazon-science/alexa-teacher-models#5]
... even though I didn't even make use of the SageMaker Notebook the tutorial asked me to setup.

This is pretty shocking. I'm trying to contact support. (Case ID: 11431751141) And yes, the invoice specifically lists the costs under SageMaker.

I'm putting up this post as a warning to others who may follow the tutorial and accidentally run into this issue.

**Comment by jgmf-amazon** [comment]
Hi @JPhilipp , I’m sorry to hear about your experience, and I would be happy to help track down the issue. The AWS support team, whom you've already contacted, will discuss the cost issues with you, but I can help with root causing.

Could you please tell me a little more about this statement? “I didn’t even make use of the SageMaker Notebook the tutorial asked me to setup.” How did you set up the model?

Currently our example notebook destroys the endpoint in the last cell. Could you please verify that you do not have any endpoints still running? They would be located under the “Inference” menu item on the left side of the SageMaker console.

**Comment by JPhilipp** [comment]
Thanks for the amazingly fast reply. For reference, the Billing Support told me to contact Tech Support (I am already paying for Developer Support), and the new Case Id is 11431958191. Billing Support told me the costs were listed as "Hosting ml.g4dn.12xlarge hour in EU (Frankfurt)". They say I should fix any Tech Issues before solving it with them.

I set up the model just like the tutorial guided me to, please excuse me if I'm using possibly wrong wording like "Notebook" (I was thinking of that Collab-like thing) -- maybe I should have called it "Model". In either case, clicking through all sub-items in the Inference navigation menu (including the "Models" entry), it's all coming up empty.

On a side note, one thing I noticed during the original setup was that it didn't work and resulted in an endless spinner after clicking Launch App -> Studio. (For reference, [see my Reddit comment](https://www.reddit.com/r/GPT3/comments/yyqw0t/gpt3_vs_alexatm/) from 14 days ago.) I finally had to close the browser after what might have been 5-10 minutes. The next day it worked. Maybe this glitch is what caused the billing issue?

Thanks a lot!

**Comment by jgmf-amazon** [comment]
Hi @JPhilipp , hmm, I see. I wouldn't expect such costs from the domain launch or studio launch of SageMaker. The magnitude of this cost sounds like a GPU instance has been running for weeks. 

If you open your "studio" in SageMaker and then click on the icon on the left that's a circle with a square inside, do you see anything under "Running Instances"?

**Comment by JPhilipp** [comment]
Thanks, this is what I see when I click Studio -- I can't seem to spot a circle with a square inside immediately? By the way, I did create a domain in the past, by following the mentioned tutorial here. 

![image](https://user-images.githubusercontent.com/1754503/205362900-11686428-19ff-4f8c-b788-f5057f86290a.png)

(For reference, that's the same account where when I click on "Billing", I get the 2k SageMaker invoice.)

**Comment by JPhilipp** [comment]
Ah, I get something when I switch to Frankfurt in the top Regions. Now I can click "Open Studio". There under Deployments, I can find an Endpoint, presumably the one I made during the tutorial steps. It says "In Service". I'm trying to find a way to Cancel it now.

**Comment by jgmf-amazon** [comment]
Ah, yes, you should be able to delete the endpoint from that same screen where it's listed as `In Service`

**Comment by JPhilipp** [comment]
Thanks. This is amazingly scary. I did not know by following this tutorial that such immense costs would occur if one doesn't know everything about how it works. ("Teacher Model" and "noncommercial use" made me relax, if anything.) This being, presumably, a first-user beginner tutorial.

I picked File -> Shutdown and hope this cleared everything now, but am not sure. Clicking on "Studio" again now to confirm nothing is running in fact now creates another Studio instance. Ouch.

**Comment by jgmf-amazon** [comment]
Hi @JPhilipp , thanks for the feedback and sorry again for the experience. I trust that you can hammer out a solution on the cost front with your AWS support team.

We are now adding more warnings, etc, to the notebooks and the tutorials to help prevent this from happening to others.

**Comment by JPhilipp** [comment]
Thanks for your fast replies. Is there any way I can confirm no endpoint is still running, without clicking "Open Studio" again (as that seems to create a fresh running instance, right)?

**Comment by jgmf-amazon** [comment]
Absolutely. The endpoints should be viewable directly from `Inference` > `Endpoints` on the left side of the home sagemaker page: 
<img width="285" alt="image" src="https://user-images.githubusercontent.com/76265524/205365778-5f290975-d72e-4ef7-9278-340be97e7453.png">

**Comment by JPhilipp** [comment]
Ah thanks. So the scariness doesn't end -- it was still showing as active, even though I had clicked File -> Shutdown before. (Careful: One needs to go through every Region listed at the top to find potentially still running ones.) I've now selected the Action "Delete" from that overview.

Thanks again! Please note I'm looking at this from the point of view of an indie developer who followed a beginner tutorial, so you can probably imagine how a) $2000 is a scary sum (and could be bankrupting to some), and b) I don't know all the ins and outs of how it works, hence why I followed the tutorial. All I had wanted to do was to have something I can use like I'm currently using the GPT-3 API, to be honest.

Thanks for the fast replies, once more.

**Comment by jgmf-amazon** [comment]
Yes, agreed on all fronts. We are actively working on additional guardrails, and I hope that for your particular case you can arrive at a good solution with AWS support. Thanks, and sorry again.

**Comment by JPhilipp** [comment]
Thanks. I will reply again in this thread when I have an update on the refund front.

**Comment by JPhilipp** [comment]
If I may make one final suggestion in regards to how a potential Readme warning could look like:
- At the top of the tutorial steps (so that it can't be glossed over if one only follows half-way)
- In red (easier to see)
- Very short (increasing the chance it will be read), e.g. "Careful: Delete the endpoint afterwards to not create high costs!"
- With a final last step at the tutorial repeating the info.

Ok, now I'll try to relax a bit. Cheers. :)

**Comment by JPhilipp** [comment]
Update: The fantastic Amazon support guided me to setting up billing alerts, removing all running instances, and ultimately refunded the bill -- absolutely amazing support from all of you.

Thank you very much for your help, which was also crucial in resolving this!

Gotta say, THIS is why I love using Amazon as platform. They never disappointed me in customer service!
